#!/usr/bin/env python3
"""Regenerates docs/CHALLENGE_MAP.md from src/carbot_bringup/config/data/challenges.yaml.

    python3 tools/gen_challenge_map.py
The YAML is the source of truth; never edit the generated table by hand.
"""
import os

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src', 'carbot_bringup', 'config', 'data', 'challenges.yaml')
OUT = os.path.join(ROOT, 'docs', 'CHALLENGE_MAP.md')

TAB_NAMES = {   # phase 7 GUI tab titles (YAML ids unchanged; see carbot_gui.gui_core.YAML_TAB_ALIASES)
    'main': 'Drive', 'map': 'Global map', 'perception': 'Perception + planner',
    'planner': 'Perception + planner', 'memory_lidar': 'Memory + LiDAR', 'localization': 'Localization',
    'detections': 'Detections', 'control': 'Control + safety', 'health': 'System health',
    'tuning': 'Tuning', 'events': 'Events + log', 'scoreboard': 'Events + log', 'recording': 'Events + log',
}


def main():
    doc = yaml.safe_load(open(SRC, encoding='utf-8'))
    total = sum(c['marks'][0] for c in doc['challenges'])
    lines = [
        '# Challenge map',
        '',
        'Generated by `tools/gen_challenge_map.py` from '
        '`src/carbot_bringup/config/data/challenges.yaml`. Do not edit by hand.',
        '',
        'Marks are EXCELLENT / COMPLETED / PARTIAL / FAIL from the rulebook rubric. '
        'Any manual intervention (touch, e-stop, reset, reposition) scores 0 for that '
        'challenge; timer-based traffic-light logic scores 0. The rulebook allows '
        'pre-recorded motion for parking only, but we do not use it: parking (block 11) '
        'is a Reeds-Shepp manoeuvre planned into the observed bay from the estimated pose.',
        '',
        f'Maximum total: **{total}** marks.',
        '',
        '| # | Challenge | Marks | Nodes | Parameters | GUI tab |',
        '|---|---|---|---|---|---|',
    ]
    for c in doc['challenges']:
        marks = ' / '.join(str(m) for m in c['marks'])
        nodes = ', '.join(f'`{n}`' for n in c.get('nodes', []))
        params = ', '.join(f'`{p}`' for p in c.get('params', []))
        tab = TAB_NAMES.get(c.get('tab', ''), c.get('tab', ''))
        lines.append(f"| {c['id']} | {c['name']} | {marks} | {nodes} | {params} | {tab} |")
    lines.append('')
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'wrote {OUT} ({len(doc["challenges"])} challenges, {total} marks)')


if __name__ == '__main__':
    main()
